spring:
  application:
    name: SpringBootMessagingApp

  devtools:
    restart:
      trigger-file: true

server:
  port: 9090
  use-forward-headers: false



twilio:
  account_sid: AC3942b9ea22a4e393479c6a6a5da58fd9
  auth_token: 281d495ac3bffd14de634d4ba49cd2cc
  trial_number: +12055831841