spring:
  application:
    name: SpringBootMessagingApp
  data:
    mongodb:
      host: localhost
      port: 27017
      #mongodb://dhiren:dhiren13@ds251894.mlab.com:51894/mydemodb
  devtools:
    restart:
      trigger-file: true
#  security:
#    user:
#      name: dhiren
#      password: November@13

server:
  port: 9090
  use-forward-headers: false

otp:
  expiration:
    time: 120000

twilio:
  account_sid: AC3942b9ea22a4e393479c6a6a5da58fd9
  auth_token: 281d495ac3bffd14de634d4ba49cd2cc
  trial_number: +12055831841
